## Getting 5 years Alpaca API then Yfinance API daily data for NVDA, GOOG, MMM, and PG for comparison, then saved to CSV in Resources folder.

In [1]:
# Initial Imports
import os
import requests
import pandas as pd
from dotenv import load_dotenv
import alpaca_trade_api as tradeapi

%matplotlib inline

#### Put your own "my.env" in the root directory (same as notebook)

In [2]:
# Load .env environment variables
load_dotenv('my.env')

True

In [3]:
# Set Alpaca API key and secret
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

In [4]:
# Verify that Alpaca key and secret were correctly loaded
print(f"Alpaca Key type: {type(alpaca_api_key)}")
print(f"Alpaca Secret Key type: {type(alpaca_secret_key)}")

Alpaca Key type: <class 'str'>
Alpaca Secret Key type: <class 'str'>

In [5]:
# Create the Alpaca API object
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="v2")

In [6]:
# Format current date as ISO format
todaydate = pd.Timestamp("2024-03-28", tz="America/New_York").isoformat()
begindate = pd.Timestamp("2019-01-01", tz="America/New_York").isoformat()

In [7]:
# Set the tickers
tickers = ["NVDA", "GOOG", "MMM", "PG"]

In [8]:
# Set timeframe to one day ("1Day") for the Alpaca API
timeframe = "1Day"

In [9]:
# Get current closing prices for tickers
df_portfolio = alpaca.get_bars(
    tickers,
    timeframe,
    start = begindate,
    end = todaydate
).df

# Display sample data
df_portfolio

,close,high,low,trade_count,open,volume,vwap,symbol
timestamp,,,,,,,,
2019-01-02 05:00:00+00:00,1045.85,1052.3200,1015.7100,29323,1016.57,1690914,1038.633069,GOOG
2019-01-03 05:00:00+00:00,1016.06,1056.9800,1014.0700,36230,1041.00,2131697,1023.155931,GOOG
2019-01-04 05:00:00+00:00,1070.71,1070.8400,1027.4179,38175,1032.59,2359140,1060.926609,GOOG
2019-01-07 05:00:00+00:00,1068.39,1073.9999,1054.7600,37361,1071.50,2194872,1066.211128,GOOG
2019-01-08 05:00:00+00:00,1076.28,1084.5600,1060.5300,28160,1076.11,2031189,1073.678880,GOOG
...,...,...,...,...,...,...,...,...
2024-03-22 04:00:00+00:00,161.66,162.4100,161.4700,65644,162.20,6393425,161.755222,PG
2024-03-25 04:00:00+00:00,160.19,161.6600,159.7300,87367,161.17,7145692,160.270983,PG
2024-03-26 04:00:00+00:00,160.55,161.1400,160.1400,69752,160.36,5842850,160.616560,PG
2024-03-27 04:00:00+00:00,162.61,162.7400,161.3400,79449,161.36,6599711,162.338397,PG
2024-03-28 04:00:00+00:00,162.25,163.1400,161.7000,75431,162.82,7191571,162.311598,PG

In [10]:
df_portfolio.to_csv('Resources/Alpaca_stocks_5yr_daily.csv', index=True)

# Now with Yfinance
#### Note: this returns multilevel column names but there is a [StackOverflow]("https://stackoverflow.com/questions/63107594/how-to-deal-with-multi-level-column-names-downloaded-with-yfinance/63107801#63107801") article on how to deal with them in a variety of ways.

In [11]:
import yfinance as yf

# Set the tickers
tickers = ["NVDA", "GOOG", "MMM", "PG"]

# Set the timeframe
timeframe = "1d"

# Set the start and end dates
start_date = "2019-01-01"
end_date = "2024-03-28"

# Retrieve the data using yfinance
df_portfolio_yfinance = yf.download(tickers, 
                           start=start_date, 
                           end=end_date, 
                           interval=timeframe,
                           group_by='ticker')

# Display the data
df_portfolio_yfinance

[*********************100%%**********************]  4 of 4 completed

Ticker            GOOG                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2019-01-02   50.828499   52.616001   50.785500   52.292500   52.292500
2019-01-03   52.049999   52.848999   50.703499   50.803001   50.803001
2019-01-04   51.629501   53.542000   51.370899   53.535500   53.535500
2019-01-07   53.575001   53.700001   52.737999   53.419498   53.419498
2019-01-08   53.805500   54.228001   53.026501   53.813999   53.813999
...                ...         ...         ...         ...         ...
2024-03-21  150.320007  151.304993  148.009995  148.740005  148.740005
2024-03-22  150.240005  152.559998  150.089996  151.770004  151.770004
2024-03-25  150.949997  151.455994  148.800003  151.149994  151.149994
2024-03-26  151.240005  153.199997  151.029999  151.699997  151.699997
2024-03-27  152.145004  152.690002  150.130005  151.940002  151.940002

Ticker                      NVDA                                      ...  \
Price         Volume        Open        High         Low       Close  ...
Date                                                                  ...
2019-01-02  30652000   32.660000   34.619999   32.512501   34.055000  ...
2019-01-03  36822000   33.447498   33.790001   31.922501   31.997499  ...
2019-01-04  41878000   32.735001   34.432499   32.424999   34.047501  ...
2019-01-07  39638000   34.625000   36.222500   34.107498   35.849998  ...
2019-01-08  35298000   36.672501   36.695000   34.224998   34.957500  ...
...              ...         ...         ...         ...         ...  ...
2024-03-21  19843900  923.000000  926.479980  904.049988  914.349976  ...
2024-03-22  19226300  911.409973  947.780029  908.340027  942.890015  ...
2024-03-25  15114700  939.409973  967.659973  935.099976  950.020020  ...
2024-03-26  19312700  958.510010  963.750000  925.020020  925.609985  ...
2024-03-27  16622000  931.119995  932.400024  891.229980  902.500000  ...

Ticker              PG                                           MMM  \
Price              Low       Close   Adj Close    Volume        Open
Date
2019-01-02   89.930000   91.279999   79.923477   9843900  157.040131
2019-01-03   90.379997   90.639999   79.363098   9820200  157.424744
2019-01-04   90.370003   92.489998   80.982956  10565700  156.145493
2019-01-07   91.400002   92.120003   80.658989   9012500  160.000000
2019-01-08   91.820000   92.459999   80.956665   9551300  161.371231
...                ...         ...         ...       ...         ...
2024-03-21  161.119995  161.860001  161.860001   5211500   90.468224
2024-03-22  161.470001  161.660004  161.660004   6393200   89.966553
2024-03-25  159.729996  160.190002  160.190002   7145600   88.545151
2024-03-26  160.139999  160.550003  160.550003   5842700   87.006691
2024-03-27  161.339996  162.610001  162.610001   6599700   86.120399

Ticker
Price             High         Low       Close   Adj Close   Volume
Date
2019-01-02  159.690628  156.103683  159.657196  123.031563  2960339
2019-01-03  157.424744  152.918060  153.645493  118.398956  4016407
2019-01-04  160.518402  155.543472  159.966553  123.269951  3582140
2019-01-07  160.785950  157.742477  159.598663  122.986481  2585991
2019-01-08  162.299332  158.511703  160.267563  123.501900  2965841
...                ...         ...         ...         ...      ...
2024-03-21   91.295990   90.125420   90.192307   90.192307  7886663
2024-03-22   90.401337   89.255852   89.280937   89.280937  5321243
2024-03-25   89.306023   87.608696   87.658859   87.658859  6680019
2024-03-26   87.516724   85.618729   85.811035   85.811035  7279693
2024-03-27   87.591972   86.112038   87.449837   87.449837  4641676

[1318 rows x 24 columns]

In [12]:
# Writing df to CSV for manual review 
df_portfolio_yfinance.to_csv('Resources/yfinance_stocks_5yr_daily_groupby_ticker.csv', index=True)

In [13]:
# Getting info for a single stock "NVDA"
nvda = yf.Ticker("NVDA")

# get all stock info
nvda.info

{'address1': '2788 San Tomas Expressway',
 'city': 'Santa Clara',
 'state': 'CA',
 'zip': '95051',
 'country': 'United States',
 'phone': '408 486 2000',
 'website': 'https://www.nvidia.com',
 'industry': 'Semiconductors',
 'industryKey': 'semiconductors',
 'industryDisp': 'Semiconductors',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "NVIDIA Corporation provides graphics and compute and networking solutions in the United States, Taiwan, China, Hong Kong, and internationally. The Graphics segment offers GeForce GPUs for gaming and PCs, the GeForce NOW game streaming service and related infrastructure, and solutions for gaming platforms; Quadro/NVIDIA RTX GPUs for enterprise workstation graphics; virtual GPU or vGPU software for cloud-based visual and virtual computing; automotive platforms for infotainment systems; and Omniverse software for building and operating metaverse and 3D internet applications. The Compute & Networking segment comprises Data Center computing platforms and end-to-end networking platforms, including Quantum for InfiniBand and Spectrum for Ethernet; NVIDIA DRIVE automated-driving platform and automotive development agreements; Jetson robotics and other embedded platforms; NVIDIA AI Enterprise and other software; and DGX Cloud software and services. The company's products are used in gaming, professional visualization, data center, and automotive markets. It sells its products to original equipment manufacturers, original device manufacturers, system integrators and distributors, independent software vendors, cloud service providers, consumer internet companies, add-in board manufacturers, distributors, automotive manufacturers and tier-1 automotive suppliers, and other ecosystem participants. NVIDIA Corporation was incorporated in 1993 and is headquartered in Santa Clara, California.",
 'fullTimeEmployees': 29600,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jen-Hsun  Huang',
   'age': 60,
   'title': 'Co-Founder, CEO, President & Director',
   'yearBorn': 1963,
   'fiscalYear': 2023,
   'totalPay': 1690542,
   'exercisedValue': 442805504,
   'unexercisedValue': 94833752},
  {'maxAge': 1,
   'name': 'Ms. Colette M. Kress',
   'age': 56,
   'title': 'Executive VP & CFO',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 912551,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Debora  Shoquist',
   'age': 68,
   'title': 'Executive Vice President of Operations',
   'yearBorn': 1955,
   'fiscalYear': 2023,
   'totalPay': 870785,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Timothy S. Teter',
   'age': 56,
   'title': 'Executive VP, General Counsel & Secretary',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 862709,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ajay K. Puri',
   'age': 68,
   'title': 'Executive Vice President of Worldwide Field Operations',
   'yearBorn': 1955,
   'fiscalYear': 2023,
   'totalPay': 993707,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris A. Malachowsky',
   'title': 'Co-Founder',
   'fiscalYear': 2023,
   'totalPay': 320000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Donald F. Robertson Jr.',
   'age': 54,
   'title': 'VP & Chief Accounting Officer',
   'yearBorn': 1969,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Prof. William J. Dally',
   'age': 62,
   'title': 'Chief Scientist & Senior VP of Research',
   'yearBorn': 1961,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Simona  Jankowski C.F.A., J.D.',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Robert  Sherbin',
   'age': 64,
   'title': 'Vice President of Corporate Communications',
   'yearBorn': 1959,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 6,
 'boardRisk': 9,
 'compensationRisk': 1,
 'shareHolderRightsRisk': 8,
 'overallRisk': 8,
 'governanceEpochDate': 1711670400,
 'compensationAsOfEpochDate': 1703980800,
 'irWebsite': 'http://phx.corporate-ir.net/phoenix.zhtml?c=116466&p=irol-IRHome',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 903.56,
 'open': 903.67,
 'dayLow': 892.04,
 'dayHigh': 922.25,
 'regularMarketPreviousClose': 903.56,
 'regularMarketOpen': 903.67,
 'regularMarketDayLow': 892.04,
 'regularMarketDayHigh': 922.25,
 'dividendRate': 0.16,
 'dividendYield': 0.0002,
 'exDividendDate': 1709596800,
 'payoutRatio': 0.0134000005,
 'fiveYearAvgDividendYield': 0.13,
 'beta': 1.725,
 'trailingPE': 75.74434,
 'forwardPE': 29.754032,
 'volume': 44336598,
 'regularMarketVolume': 44336598,
 'averageVolume': 54023118,
 'averageVolume10days': 54244810,
 'averageDailyVolume10Day': 54244810,
 'marketCap': 2259074940928,
 'fiftyTwoWeekLow': 262.2,
 'fiftyTwoWeekHigh': 974.0,
 'priceToSalesTrailing12Months': 37.081432,
 'fiftyDayAverage': 776.0034,
 'twoHundredDayAverage': 538.0484,
 'trailingAnnualDividendRate': 0.16,
 'trailingAnnualDividendYield': 0.00017707734,
 'currency': 'USD',
 'enterpriseValue': 2244146888704,
 'profitMargins': 0.48849,
 'floatShares': 2397725000,
 'sharesOutstanding': 2500000000,
 'sharesShort': 30321554,
 'sharesShortPriorMonth': 28139408,
 'sharesShortPreviousMonthDate': 1707955200,
 'dateShortInterest': 1710460800,
 'sharesPercentSharesOut': 0.0121,
 'heldPercentInsiders': 0.040009998,
 'heldPercentInstitutions': 0.68004996,
 'shortRatio': 0.49,
 'shortPercentOfFloat': 0.0126,
 'impliedSharesOutstanding': 2565929984,
 'bookValue': 17.442,
 'priceToBook': 51.80771,
 'lastFiscalYearEnd': 1706400000,
 'nextFiscalYearEnd': 1738022400,
 'mostRecentQuarter': 1706400000,
 'earningsQuarterlyGrowth': 7.688,
 'netIncomeToCommon': 29760000000,
 'trailingEps': 11.93,
 'forwardEps': 30.37,
 'pegRatio': 0.98,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1626739200,
 'enterpriseToRevenue': 36.836,
 'enterpriseToEbitda': 65.085,
 '52WeekChange': 2.2915528,
 'SandP52WeekChange': 0.27878118,
 'lastDividendValue': 0.04,
 'lastDividendDate': 1709596800,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'NVDA',
 'underlyingSymbol': 'NVDA',
 'shortName': 'NVIDIA Corporation',
 'longName': 'NVIDIA Corporation',
 'firstTradeDateEpochUtc': 917015400,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': '7f5f6a07-b148-30f4-98a2-2caa3df2aed0',
 'messageBoardId': 'finmb_32307',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 903.63,
 'targetHighPrice': 2762.12,
 'targetLowPrice': 478.4,
 'targetMeanPrice': 979.64,
 'targetMedianPrice': 960.0,
 'recommendationMean': 1.7,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 46,
 'totalCash': 25984000000,
 'totalCashPerShare': 10.394,
 'ebitda': 34480001024,
 'totalDebt': 11056000000,
 'quickRatio': 3.385,
 'currentRatio': 4.171,
 'totalRevenue': 60921999360,
 'debtToEquity': 25.725,
 'revenuePerShare': 24.675,
 'returnOnAssets': 0.38551,
 'returnOnEquity': 0.91458,
 'freeCashflow': 19866875904,
 'operatingCashflow': 28089999360,
 'earningsGrowth': 7.613,
 'revenueGrowth': 2.653,
 'grossMargins': 0.72718,
 'ebitdaMargins': 0.56597,
 'operatingMargins': 0.61592996,
 'financialCurrency': 'USD',
 'trailingPegRatio': 1.2185}

In [14]:
# Calling historical market data for NVDA
nvda_hist = nvda.history(period="5y")

In [15]:
# show meta information about the history (requires history() to be called first)
nvda.history_metadata

{'currency': 'USD',
 'symbol': 'NVDA',
 'exchangeName': 'NMS',
 'fullExchangeName': 'NasdaqGS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 917015400,
 'regularMarketTime': 1712001600,
 'hasPrePostMarketData': True,
 'gmtoffset': -14400,
 'timezone': 'EDT',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 903.63,
 'fiftyTwoWeekHigh': 922.25,
 'fiftyTwoWeekLow': 892.04,
 'regularMarketDayHigh': 922.25,
 'regularMarketDayLow': 892.04,
 'regularMarketVolume': 44336598,
 'chartPreviousClose': 45.57,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EDT',
   'end': 1712064600,
   'start': 1712044800,
   'gmtoffset': -14400},
  'regular': {'timezone': 'EDT',
   'end': 1712088000,
   'start': 1712064600,
   'gmtoffset': -14400},
  'post': {'timezone': 'EDT',
   'end': 1712102400,
   'start': 1712088000,
   'gmtoffset': -14400}},
 'dataGranularity': '1d',
 'range': '5y',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

## Pulling Financials data for NVDA.  Note that `income_stmt` seems to pull annual, and `quarterly_income_stmt` pulls quarterly.

In [16]:
# Showing Financials for NVDA

# - income statement
nvda.income_stmt
nvda.quarterly_income_stmt

,2024-01-31,2023-10-31,2023-07-31,2023-04-30,2023-01-31
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0,0.0
Tax Rate For Calcs,0.129094,0.122,0.114,0.075,0.21
Normalized EBITDA,14556000000.0,10957000000.0,7411000000.0,2659000000.0,1778000000.0
Total Unusual Items,0.0,0.0,0.0,0.0,0.0
Total Unusual Items Excluding Goodwill,0.0,0.0,0.0,0.0,0.0
Net Income From Continuing Operation Net Minority Interest,12285000000.0,9243000000.0,6188000000.0,2043000000.0,1414000000.0
Reconciled Depreciation,387000000.0,372000000.0,365000000.0,384000000.0,426000000.0
Reconciled Cost Of Revenue,5312000000.0,4720000000.0,4045000000.0,2544000000.0,2218000000.0
EBITDA,14556000000.0,10957000000.0,7411000000.0,2659000000.0,1778000000.0
EBIT,14169000000.0,10585000000.0,7046000000.0,2275000000.0,1352000000.0
Net Interest Income,231000000.0,171000000.0,122000000.0,84000000.0,51000000.0
Interest Expense,63000000.0,63000000.0,65000000.0,66000000.0,64000000.0
Interest Income,294000000.0,234000000.0,187000000.0,150000000.0,115000000.0
Normalized Income,12285000000.0,9243000000.0,6188000000.0,2043000000.0,1414000000.0
Net Income From Continuing And Discontinued Operation,12285000000.0,9243000000.0,6188000000.0,2043000000.0,1414000000.0
Total Expenses,8489000000.0,7703000000.0,6707000000.0,5052000000.0,4795000000.0
Total Operating Income As Reported,13614000000.0,10417000000.0,6800000000.0,2140000000.0,1256000000.0
Diluted Average Shares,NaN,2494000000.0,2499000000.0,2490000000.0,2477000000.0
Basic Average Shares,NaN,2468000000.0,2473000000.0,2470000000.0,2464000000.0
Diluted EPS,NaN,3.71,2.48,0.82,0.57
Basic EPS,NaN,3.75,2.5,0.83,0.57
Diluted NI Availto Com Stockholders,12285000000.0,9243000000.0,6188000000.0,2043000000.0,1414000000.0
Net Income Common Stockholders,12285000000.0,9243000000.0,6188000000.0,2043000000.0,1414000000.0
Net Income,12285000000.0,9243000000.0,6188000000.0,2043000000.0,1414000000.0
Net Income Including Noncontrolling Interests,12285000000.0,9243000000.0,6188000000.0,2043000000.0,1414000000.0
Net Income Continuous Operations,12285000000.0,9243000000.0,6188000000.0,2043000000.0,1414000000.0
Tax Provision,1821000000.0,1279000000.0,793000000.0,166000000.0,-126000000.0
Pretax Income,14106000000.0,10522000000.0,6981000000.0,2209000000.0,1288000000.0
Other Income Expense,261000000.0,-66000000.0,59000000.0,-15000000.0,-19000000.0
Other Non Operating Income Expenses,261000000.0,-66000000.0,59000000.0,-15000000.0,-19000000.0
Special Income Charges,0.0,0.0,0.0,0.0,0.0
Restructuring And Mergern Acquisition,0.0,0.0,0.0,0.0,0.0
Net Non Operating Interest Income Expense,231000000.0,171000000.0,122000000.0,84000000.0,51000000.0
Interest Expense Non Operating,63000000.0,63000000.0,65000000.0,66000000.0,64000000.0
Interest Income Non Operating,294000000.0,234000000.0,187000000.0,150000000.0,115000000.0
Operating Income,13614000000.0,10417000000.0,6800000000.0,2140000000.0,1256000000.0
Operating Expense,3177000000.0,2983000000.0,2662000000.0,2508000000.0,2577000000.0
Research And Development,2465000000.0,2294000000.0,2040000000.0,1875000000.0,1952000000.0
Selling General And Administration,712000000.0,689000000.0,622000000.0,633000000.0,625000000.0
Gross Profit,16791000000.0,13400000000.0,9462000000.0,4648000000.0,3833000000.0
Cost Of Revenue,5312000000.0,4720000000.0,4045000000.0,2544000000.0,2218000000.0
Total Revenue,22103000000.0,18120000000.0,13507000000.0,7192000000.0,6051000000.0
Operating Revenue,22103000000.0,18120000000.0,13507000000.0,7192000000.0,6051000000.0

In [17]:
# - balance sheet
nvda.balance_sheet
nvda.quarterly_balance_sheet

,2024-01-31,2023-10-31,2023-07-31,2023-04-30,2023-01-31
Treasury Shares Number,NaN,0.0,NaN,NaN,NaN
Ordinary Shares Number,2464000000.0,2466000000.0,2469000000.0,2473000000.0,2466136572.0
Share Issued,2464000000.0,2466000000.0,2469000000.0,2473000000.0,2466136572.0
Net Debt,2429000000.0,4187000000.0,3922000000.0,5875000000.0,7564000000.0
Total Debt,11056000000.0,11027000000.0,10954000000.0,12080000000.0,12031000000.0
...,...,...,...,...,...
Receivables,9999000000.0,8309000000.0,7066000000.0,4080000000.0,3827000000.0
Accounts Receivable,9999000000.0,8309000000.0,7066000000.0,4080000000.0,3827000000.0
Cash Cash Equivalents And Short Term Investments,25984000000.0,18281000000.0,16023000000.0,15320000000.0,13296000000.0
Other Short Term Investments,18704000000.0,12762000000.0,10240000000.0,10241000000.0,9907000000.0
Cash And Cash Equivalents,7280000000.0,5519000000.0,5783000000.0,5079000000.0,3389000000.0

In [18]:
# - cash flow statement
nvda.cashflow
nvda.quarterly_cashflow

# see `Ticker.get_income_stmt()` for more options

,2024-01-31,2023-10-31,2023-07-31,2023-04-30,2023-01-31
Free Cash Flow,11245000000.0,7054000000.0,6059000000.0,2663000000.0,1739000000.0
Repurchase Of Capital Stock,-2659000000.0,-3807000000.0,-3067000000.0,0.0,-1213000000.0
Repayment Of Debt,0.0,0.0,NaN,NaN,0.0
Issuance Of Debt,NaN,NaN,NaN,NaN,0.0
Capital Expenditure,-254000000.0,-278000000.0,-289000000.0,-248000000.0,-509000000.0
Income Tax Paid Supplemental Data,1873000000.0,4348000000.0,NaN,NaN,32000000.0
End Cash Position,7280000000.0,5519000000.0,5882000000.0,5079000000.0,3389000000.0
Beginning Cash Position,5519000000.0,5882000000.0,5079000000.0,3389000000.0,2800000000.0
Changes In Cash,1761000000.0,-363000000.0,803000000.0,1690000000.0,589000000.0
Financing Cash Flow,-3629000000.0,-4525000000.0,-5099000000.0,-380000000.0,-1656000000.0
Cash Flow From Continuing Financing Activities,-3629000000.0,-4525000000.0,-5099000000.0,-380000000.0,-1656000000.0
Net Other Financing Charges,-871000000.0,-777000000.0,-683000000.0,-527000000.0,-351000000.0
Proceeds From Stock Option Exercised,0.0,156000000.0,1000000.0,246000000.0,6000000.0
Cash Dividends Paid,-99000000.0,-97000000.0,-100000000.0,-99000000.0,-98000000.0
Common Stock Dividend Paid,NaN,NaN,NaN,-99000000.0,-98000000.0
Net Common Stock Issuance,-2659000000.0,-3807000000.0,-3067000000.0,0.0,-1213000000.0
Common Stock Payments,-2659000000.0,-3807000000.0,-3067000000.0,0.0,-1213000000.0
Net Issuance Payments Of Debt,0.0,0.0,NaN,NaN,0.0
Net Long Term Debt Issuance,0.0,0.0,NaN,NaN,0.0
Long Term Debt Payments,0.0,0.0,NaN,NaN,0.0
Long Term Debt Issuance,NaN,NaN,NaN,NaN,0.0
Investing Cash Flow,-6109000000.0,-3170000000.0,-446000000.0,-841000000.0,-3000000.0
Cash Flow From Continuing Investing Activities,-6109000000.0,-3170000000.0,-446000000.0,-841000000.0,-3000000.0
Net Investment Purchase And Sale,-5855000000.0,-2892000000.0,-157000000.0,-510000000.0,506000000.0
Sale Of Investment,1781000000.0,2890000000.0,2599000000.0,2512000000.0,2633000000.0
Purchase Of Investment,-7636000000.0,-5782000000.0,-2756000000.0,-3022000000.0,-2127000000.0
Net Business Purchase And Sale,0.0,0.0,0.0,-83000000.0,0.0
Purchase Of Business,0.0,0.0,0.0,-83000000.0,0.0
Net PPE Purchase And Sale,-254000000.0,-278000000.0,-289000000.0,-248000000.0,-509000000.0
Purchase Of PPE,-254000000.0,-278000000.0,-289000000.0,-248000000.0,-509000000.0
Operating Cash Flow,11499000000.0,7332000000.0,6348000000.0,2911000000.0,2248000000.0
Cash Flow From Continuing Operating Activities,11499000000.0,7332000000.0,6348000000.0,2911000000.0,2248000000.0
Change In Working Capital,-1719000000.0,-2733000000.0,-174000000.0,904000000.0,287000000.0
Change In Other Current Liabilities,306000000.0,-28000000.0,131000000.0,105000000.0,150000000.0
Change In Payables And Accrued Expense,1353000000.0,-1261000000.0,2764000000.0,700000000.0,-27000000.0
Change In Accrued Expense,1072000000.0,-1722000000.0,1986000000.0,689000000.0,166000000.0
Change In Payable,281000000.0,461000000.0,778000000.0,11000000.0,-193000000.0
Change In Account Payable,281000000.0,461000000.0,778000000.0,11000000.0,-193000000.0
Change In Prepaid Assets,-1185000000.0,255000000.0,-377000000.0,-215000000.0,-210000000.0
Change In Inventory,-503000000.0,-456000000.0,295000000.0,566000000.0,-706000000.0
Change In Receivables,-1690000000.0,-1243000000.0,-2987000000.0,-252000000.0,1080000000.0
Changes In Account Receivables,-1690000000.0,-1243000000.0,-2987000000.0,-252000000.0,1080000000.0
Other Non Cash Items,-108000000.0,-68000000.0,-68000000.0,-34000000.0,20000000.0
Stock Based Compensation,994000000.0,979000000.0,841000000.0,735000000.0,738000000.0
Deferred Tax,-78000000.0,-530000000.0,-746000000.0,-1135000000.0,-647000000.0
Deferred Income Tax,-78000000.0,-530000000.0,-746000000.0,-1135000000.0,-647000000.0
Depreciation Amortization Depletion,387000000.0,372000000.0,365000000.0,384000000.0,426000000.0
Depreciation And Amortization,387000000.0,372000000.0,365000000.0,384000000.0,426000000.0
Operating Gains Losses,-262000000.0,69000000.0,-59000000.0,14000000.0,10000000.0
Gain Loss On Investment Securities,-262000000.0,69000000.0,-59000000.0,14000000.0,10000000.0
Net Income From Continuing Operations,12285000000.0,9243000000.0,6189000000.0,2043000000.0,1414000000.0

## Now let's try retrieving fundamental ratios from FInancialModelingPrep.com

In [19]:
# stock = 'NVDA'

# # Get the historical income statements data for NVDA
# income_stmts = requests.get("https://financialmodelingprep.com/api/v3/financials/income-statement/" + stock )
# income_stmts = income_stmts.json()
# income_stmts